# Generated by Django 2.0.9 on 2018-11-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_posts', '0003_auto_20181030_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_post',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo_post',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=2),
        ),
    ]
